plugins {
    id 'com.onesignal.androidsdk.onesignal-gradle-plugin'
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    // don't change this namespace & compileSdk version
    namespace 'nemosofts.streambox'
    compileSdk 36

    defaultConfig {
        // change this applicationId & versionName & versionCode to your own values
        applicationId "com.mubashir.streamflux"
        minSdk 23
        targetSdk 36
        versionCode 7
        versionName "7.2.19"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildTypes.each {
        it.buildConfigField 'String', 'BASE_URL', BASE_URL
        it.buildConfigField 'String', 'API_NAME', API_NAME
        it.buildConfigField 'String', 'ENC_KEY', ENC_KEY
        it.buildConfigField 'String', 'IV', IV
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig = true
        viewBinding =  true
    }

    lint {
        disable 'OldTargetApi', 'GradleDependency', 'GradleDynamicVersion'
    }

    packaging {
        resources {
            excludes += "META-INF/versions/9/OSGI-INF/MANIFEST.MF"
        }
    }
}

dependencies {
    implementation libs.bundles.nemosofts
    implementation project(':nemosofts-material')
    implementation libs.bundles.network.security
    implementation libs.androidx.multidex
    implementation libs.recyclerview
    implementation libs.androidx.palette
    implementation libs.scytale
    implementation libs.commons.io
    implementation(platform(libs.firebase.bom))
    implementation libs.bundles.firebase
    implementation libs.oneSignal
    implementation libs.androidx.activity
    implementation libs.bundles.youtubeplayer
    implementation libs.admob
    implementation libs.bundles.media3
    implementation libs.media3.datasource.okhttp
    implementation(libs.bundles.exoplayer)
    testImplementation(libs.junit)
    androidTestImplementation(libs.ext.junit)
    androidTestImplementation(libs.espresso.core)
}